### PR TITLE
#4 fix: change boxcast and add velocity epsilon

### LINKED ISSUE #4: Double jump not working correctly
**Describe the bug**
the number of jumps left refreshes while player is still in the air.

**To Reproduce**
1. In playmode, press the jump button a dozen times in a row.
2. Notice that the player is allowed to jump infinitely many times in the air
3. Also notice the value in serialized field that counts the number of jumps left.

**Expected behavior**
Number of jumps left should only refresh when player lands on the ground or platform 

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu

**Additional context**
Might be a problem with the raycasting in isGrounded function. After trying to build a function to check player landing, I have a suspicion that this function is not working correctly.

### PR DESCRIPTION
**Pull request by asim-shrestha**
closes #4

### CODE REVIEW

File: Assets/Scripts/Player.cs [hunk 1]
```diff
@@ -59,16 +59,18 @@ public class Player : NetworkBehaviour {
...
-			boxCollider.bounds.size / 2,
+			boxCollider.bounds.size,
 			0f,
 			Vector2.down,
-			1f,
+			extraHeight,
 			LayerMask.GetMask("Ground")
 		);
-		return raycast.collider != null && rb.velocity.y <= 0;
+		float velocityEpsilon = 0.01f;
```
Comment (seannam1218) [inline Assets/Scripts/Player.cs:72]: small difference, big consequences XD good catch

**Review by seannam1218 — APPROVED** [review]
